-- MySQL Script generated by MySQL Workbench
-- Thu Jun 15 21:53:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`status` (
  `idstatus` INT NOT NULL,
  `status` VARCHAR(15) NOT NULL,
  `gasto_asociado_min` INT NOT NULL,
  PRIMARY KEY (`idstatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `codigopucp` INT NOT NULL,
  `correopucp` VARCHAR(45) NOT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `status_idstatus` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_usuario_status1_idx` (`status_idstatus` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_status1`
    FOREIGN KEY (`status_idstatus`)
    REFERENCES `mydb`.`status` (`idstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_credenciales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_credenciales` (
  `idusuario` INT NOT NULL,
  `codigo` VARCHAR(45) NULL,
  `contrasenia` VARCHAR(45) NULL,
  `contrasenia_hasheada` VARCHAR(45) NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `usuario_idusuario`),
  INDEX `fk_usuario_credenciales_usuario_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_credenciales_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`viajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`viajes` (
  `idviajes` INT NOT NULL,
  `fecha_reserva` DATE NOT NULL,
  `fecha_viaje` DATE NOT NULL,
  `ciudad_origen` VARCHAR(45) NOT NULL,
  `ciudad_destino` VARCHAR(45) NOT NULL,
  `empresa_seguro` VARCHAR(45) NOT NULL,
  `cantidad_boletos` INT NOT NULL,
  `costo_total` INT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idviajes`),
  INDEX `fk_viajes_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_viajes_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
