-- MySQL Script generated by MySQL Workbench
-- Sat Jun 17 22:53:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `codigopucp` VARCHAR(8) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `correopucp` VARCHAR(45) NOT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `status` VARCHAR(20) NULL,
  PRIMARY KEY (`codigopucp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`viajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`viajes` (
  `idviajes` INT NOT NULL,
  `fecha_reserva` VARCHAR(20) NOT NULL,
  `fecha_viaje` VARCHAR(20) NOT NULL,
  `ciudad_origen` VARCHAR(45) NOT NULL,
  `ciudad_destino` VARCHAR(45) NOT NULL,
  `empresa_seguro` VARCHAR(45) NOT NULL,
  `cantidad_boletos` INT NOT NULL,
  `costo_total` INT NULL,
  `usuario_codigopucp` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idviajes`),
  INDEX `fk_viajes_usuario_idx` (`usuario_codigopucp` ASC) VISIBLE,
  CONSTRAINT `fk_viajes_usuario`
    FOREIGN KEY (`usuario_codigopucp`)
    REFERENCES `mydb`.`usuario` (`codigopucp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
